package store

import (
	"context"
	"errors"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// CustomMonster is a DM-authored monster template, owned by a single user.
// Unlike official Monster documents (keyed by {name, edition}, globally
// unique), custom monsters are identified by id — names are not unique
// across owners, since two DMs may independently create a "Goblin".
type CustomMonster struct {
	ID                 string `bson:"id"                            json:"id"`
	Name               string `bson:"name"                          json:"name"`
	Edition            string `bson:"edition"                       json:"edition"`
	MaxHP              int    `bson:"max_hp"                        json:"max_hp"`
	InitiativeModifier *int   `bson:"initiative_modifier,omitempty" json:"initiative_modifier,omitempty"`
	IsCustom           bool   `bson:"is_custom"                     json:"is_custom"`
	Private            bool   `bson:"private"                       json:"private"`
	OwnerID            string `bson:"owner_id"                      json:"owner_id"`
	OwnerDisplayName   string `bson:"owner_display_name"            json:"owner_display_name"`
	SourceType         string `bson:"source_type,omitempty"         json:"source_type,omitempty"`
	ReferenceURL       string `bson:"reference_url,omitempty"       json:"reference_url,omitempty"`
	PDFObjectKey       string `bson:"pdf_object_key,omitempty"      json:"pdf_object_key,omitempty"`
}

// CustomMonsterStore wraps the custom_monsters MongoDB collection.
type CustomMonsterStore struct {
	col *mongo.Collection
}

var GlobalCustomMonsters CustomMonsterStore

// CreateCustomMonster inserts a new DM-authored monster. If m.ID is already
// set (pre-generated by the caller, e.g. to key an uploaded PDF), it is used
// as-is; otherwise a new id is generated. The insert is mirrored into
// Typesense on a best-effort basis.
func (s *CustomMonsterStore) CreateCustomMonster(m CustomMonster) (CustomMonster, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if m.ID == "" {
		m.ID = NewID(8)
	}
	m.IsCustom = true
	if _, err := s.col.InsertOne(ctx, m); err != nil {
		return CustomMonster{}, err
	}
	syncCustomMonsterToTypesense(m)
	return m, nil
}

// GetCustomMonsterByID returns the custom monster with the given id, or nil if not found.
func (s *CustomMonsterStore) GetCustomMonsterByID(id string) (*CustomMonster, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	var m CustomMonster
	err := s.col.FindOne(ctx, bson.M{"id": id}).Decode(&m)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// UpdateCustomMonster replaces the fields of an existing custom monster in
// place, keyed by id. Callers must verify ownership first, and must
// populate m.OwnerID/OwnerDisplayName (typically copied from the existing
// document) since this performs a full document replace. The change is
// mirrored into Typesense on a best-effort basis.
func (s *CustomMonsterStore) UpdateCustomMonster(id string, m CustomMonster) (CustomMonster, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	m.ID = id
	m.IsCustom = true
	opts := options.FindOneAndReplace().SetReturnDocument(options.After)
	var result CustomMonster
	if err := s.col.FindOneAndReplace(ctx, bson.M{"id": id}, m, opts).Decode(&result); err != nil {
		return CustomMonster{}, err
	}
	syncCustomMonsterToTypesense(result)
	return result, nil
}

// DeleteCustomMonster removes the document by id and best-effort removes its
// Typesense mirror (failure to remove from Typesense is logged, not returned).
func (s *CustomMonsterStore) DeleteCustomMonster(id string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if _, err := s.col.DeleteOne(ctx, bson.M{"id": id}); err != nil {
		return err
	}
	deleteTypesenseDoc(id)
	return nil
}

// ListCustomMonstersByOwner returns all custom monsters (public or private)
// owned by ownerID, optionally filtered to a single edition when edition is
// non-empty.
func (s *CustomMonsterStore) ListCustomMonstersByOwner(ownerID string, edition string) ([]CustomMonster, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	filter := bson.M{"owner_id": ownerID}
	if edition != "" {
		filter["edition"] = edition
	}
	cursor, err := s.col.Find(ctx, filter)
	if err != nil {
		return nil, err
	}
	var results []CustomMonster
	if err := cursor.All(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}
